blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from acounts.views import (login_view, logout_view, register_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$',"posts.views.loginpage"),
    url(r'^bootstrap/$',TemplateView.as_view(template_name='bootstrap/example.html')),
    
    url(r'^comment/',include("comment.urls", namespace='comment')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/',logout_view,name='logout'),
    url(r'^register/',register_view,name='register'),
    url(r'^',include("posts.urls", namespace='posts')),
   # url(r'^login/$',auth_views.login, name='login'),
    #url(r'^logout/$',auth_views.logout,{'next_page':'/login'}, name='logout'),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
	list_details,
	create,
	delete_,
	update_,
	details,
	)

#below is what documentaion says
#but to remove error we pass the callable instead we are using this just to remove the error
#urlpatterns = [
#    
#    url(r'^$',"posts.views.list_details"),
#    url(r'^create/$',"posts.views.create"),
#    url(r'^delete/$',"posts.views.delete_"),
#    url(r'^update/$',"posts.views.update_"),
#    url(r'^details/$',"posts.views.details"),
#]

urlpatterns = [
    
    url(r'^$',list_details,name='list'),
    url(r'^create/$',create),
    url(r'^(?P<id>\d+)/delete/$',delete_),
    url(r'^(?P<id>\d+)/edit/$',update_, name='update'),
    url(r'^(?P<id>\d+)/$',details,name='detail'),
    #url(r'^(?P<id>\d+)/$',comment_delete, name='thread'),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.conf import settings
from markdown_deux import markdown
from django.contrib.contenttypes.models import ContentType
from django.utils.safestring import mark_safe
from comment.models import comment

class PostManager(models.Manager):
	def active(self,*args,**kwargs):
		return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())
# Create your models here.
class post(models.Model):
	title=models.CharField(max_length=120)
	content=models.TextField()
	user=models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
	draft=models.BooleanField(default=False)
	markdown=models.BooleanField(default=False)
	publish=models.DateField(auto_now=False,auto_now_add=False)
	image=models.FileField(null=True,blank=True)
	update=models.DateTimeField(auto_now=True,auto_now_add=False)
	timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)

	objects = PostManager()
	def __str__(self):
		return self.title
	@property
	def get_content_type(self):
		instance=self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type


	@property
	def comments(self):
		instance=self
		qs = comment.objects.filter_by_instance(instance)
		return qs


	def get_markdown(self):
		content=self.content
		return mark_safe(markdown(content))


	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"id": self.id})

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from . models import post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget = PagedownWidget(show_preview=False))
	publish = forms.DateField(widget = forms.SelectDateWidget)
	class Meta:
		model = post
		fields=[
		"title",
		"markdown",
		"content",
		"image",
		"draft",
		"publish",
		]

posts/views.py
from django.shortcuts import render, get_object_or_404,redirect,Http404
from django.http import HttpResponse, HttpResponseRedirect
from.forms import PostForm
from comment.form import CommentForm
from comment.models import comment as Comment
from django.contrib.contenttypes.models import ContentType
#from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
from .models import post
from django.db.models import Q

def create(request):
	if not request.user.is_authenticated():
		raise Http404 #in fututre redirect to you must login or signup to post something
	formn = PostForm(request.POST or None, request.FILES or None)
	boole=False
	#if formn.is_valid()
	if formn.is_valid():
	 #print(request.POST.get("title"))
		instance = formn.save(commit=False)
		instance.user = request.user
		instance.save()
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form" : formn,
		"bool":boole
		}
	return render(request,'forms.html',context)

#def loginpage(request):
#	return render(request,"loginview.html")

def details(request,id):
	#instance = post.objects.get(id=1)
	instance = get_object_or_404(post, id=id)

	if instance.draft:
		if not request.user.is_authenticated():
		    raise Http404
	initial_data = {
			"content_type":instance.get_content_type,
			"object_id":instance.id,
	}
	comment_form = CommentForm(request.POST or None, initial=initial_data)
	
	if comment_form.is_valid() and request.user.is_authenticated():
	    c_type = comment_form.cleaned_data.get("content_type")
	    content_type = ContentType.objects.get(model=c_type)
	    obj_id = comment_form.cleaned_data.get("object_id")
	    content_data = comment_form.cleaned_data.get("content")
	    parent_obj = None
	    try:
	    	parent_id = int(request.POST.get("parent_id"))
	    except:
	    	parent_id=None

	    if parent_id:
	    	parent_qs = Comment.objects.filter(id=parent_id)
	    	if parent_qs.exists() and parent_qs.count()==1:
	    	    parent_obj = parent_qs.first()

	    new_comment, created = Comment.objects.get_or_create(
	    							user = request.user,
	    							content_type = content_type,
	    							object_id = obj_id,
	    							content = content_data,
	    							parent = parent_obj,
	    							)
	    return HttpResponseRedirect(instance.get_absolute_url())
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	comments = instance.comments #comment.objects.filter_by_instance(instance)
	context = {
	"instance": instance,
	"title": instance.title,
	"comment":comments,
	"comment_form":comment_form,
	"form_e":form,
	}
	#print(instance.content)
	return render(request,'details.html',context)

def list_details(request):
    query_list=post.objects.active().order_by("-timestamp")
    search_query=request.GET.get('q')
    if search_query:
    	query_list =query_list.filter(
    		Q(title__icontains=search_query) |
    		Q(content__icontains=search_query) |
    		Q(user__first_name__icontains=search_query) |
    		Q(user__last_name__icontains=search_query) |
    		Q(user__username__icontains=search_query)
    		).distinct()
    paginator = Paginator(query_list, 10) # Show 25 contacts per page
    page = request.GET.get('page')
    

    try:
    	queryset = paginator.page(page)
    except PageNotAnInteger:
    	queryset = paginator.page(1)
    except EmptyPage:
    	queryset = paginator.page(paginator.num_pages)
    #return render(request, 'list.html', context)
    context={
        "obj":queryset,
        "title":"Latest Posts",
    }
    return render(request,'index.html',context)

def delete_(request,id=None):
	if not request.user.is_authenticated():
		raise Http404#in fututre change to redirect to login page if the user is not authenticated or report it.
	try:
		obj=get_object_or_404(post,id=id)
	except:
		raise Http404
	if obj.user != request.user:
		response = HttpResponse("you do not have permission")
		response.status_code = 403
		return response
	#instance = get_object_or_404(post,id=id)
	obj.delete()
	#meesage
	return redirect("posts:list")

def update_(request,id):
	if not request.user.is_authenticated():
		raise Http404#needs changes i thinl so
	#instance=get_object_or_404(post,id=id)
	try:
		instance=get_object_or_404(post,id=id)
	except:
		raise Http404
	if instance.user != request.user:
		response = HttpResponse("you do not have permission")
		response.status_code = 403
		return response
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.get_absolute_url())
	context= {
		"title":instance.title,
		"instance":instance,
		"form":form,

		}
	return render(request, "forms.html", context)





#def signup(request):
#    #contact_list = Contacts.objects.all()
#    if request.method == 'POST':
#    	form = UserCreationForm(request.POST)
#    	if form.is_valid():
#    		form.save()
#    		username = form_cleaned_data['username']
#    		password = form_cleaned_data['password']
#    		user = authenticate(username=username,password=password)
#    		login(request,user)
#    		return redirect('/posts')
#

posts/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie-edge">
	<title>{% block head%}my first product{% endblock %}</title>
	
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	
	{%block head_extra %} {% endblock head_extra %}
	<link rel="stylesheet" href="{%static 'css/base.css' %}"/> 
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
		<body>
			<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.12';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
			<div class="container">

<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{%url 'posts:list' %}"  data-toggle="tooltip" data-placement="top" title="Go to blog's View">Home</a></li>
  {%block post_detail_link%}{%endblock%}
 {%if request.user.is_authenticated %} <li class="breadcrumb-item"><a href="{%url 'posts:list' %}create">Post</a></li>

 <li class="breadcrumb-item"><a href="{%url 'logout' %}">Logout</a></li>{%endif%}
  {%if not request.user.is_authenticated %}
  <li class="breadcrumb-item"><a href="{%url 'login'  %}">Login</a></li>
  <li class="breadcrumb-item"><a href="{%url 'register' %}"  data-toggle="tooltip" data-placement="top" title="Not yet registered click here to signup">Register</a></li>
  {%endif%}
  

</ol>
			{% block content %}

			{% endblock %}
			</div>




	  <script
  src="https://code.jquery.com/jquery-1.12.2.min.js"
  integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
  crossorigin="anonymous"></script>
   
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>
 
<script type="text/javascript">

	$(document).ready(function(){
		$(".content-markdown").each(function(){
		    var content=$(this).text()
		    //console.log(content)
	        var mkd=marked(content)
	        //console.log(mkd)
	        $(this).html(mkd)	
		})
		$(".post-detail-item img").each(function(){
		    	$(this).addClass("img-fluid");
		})
		var titleinput = $("#id_title")
		//console.log(titleinput)
		
		var contentinput = $("#id_content")
		//console.log(titleinput)
		
		function setContent(value){
			var markedContent = marked(value)
			$("#Preview-content").html(markedContent)
			$("#Preview-content img").each(function(){
				$(this).addClass("img-fluid")

			})
		}
		setContent(contentinput.val())

		contentinput.keyup(function(){
			var newContent = $(this).val()
			setContent(newContent)
		})
		function setTitle(value){
			$("#Preview-title").text(titleinput.val())
		}
		setTitle(titleinput.val())
		titleinput.keyup(function(){
			var newtitle = $(this).val()
			setTitle(newtitle)
		})

		$(".comment-reply-btn").click(function(event){
			event.preventDefault();
			$(this).parent().next(".comment-reply").fadeToggle();
			//$(".comment-reply").fadeToggle();
		})

		$(".comment-delete").click(function(event){
		event.preventDefault();
			$(this).next(".comment-del").fadeToggle();
			// $("#show").click(function(){
            // $("").show();

		})

		//$(".d-flex p-2").(function(){
		//	$('#myFlexbox').show().css('display', 'flex');
		//})
			


	})
	
</script>
<script src="{% static 'js/del.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

		</body>
	
</html>

posts/templates/delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head%}{{ instance.title }} | {{ block.super }} {% endblock %}
{% block content %}
{{object}}
<div class="container col-sm-6 break-text">
   
    <
        <form method="POST" action=".">{%csrf_token%}
            <p>are you sure you want to delete "<span class="text-danger">{{obj.content}}</span> "</p>
          <input type="submit" value="Delete" class="btn btn-warning">
         <a href="{{obj.get_absolute_url}} " role="button" class="btn btn-default">Cancel</a>
         </form>
      
    </blockquote>
</div>
{% endblock %}
 {% url 'thrdel' id=com.id %}
 
    

posts/templates/details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head%}{{ instance.title }} | {{ block.super }} {% endblock %}
{%block post_detail_link%}
{% if instance.draft %}<li class="breadcrumb-item"><a href="{{instance.get_absolute_url}}edit" class="text-warning" data-toggle="tooltip" data-placement="top" title="Make your Posts live Now">Live it Now</a></li>{%endif%}
{%endblock%}
{% block content %}

<div class="container col-sm-6 break-text">
{%if instance.image %}
 <img src='{{ instance.image.url }}' class="img-fluid" alt="Responsive image" style="width: 100%" />
{%endif%}
<p>Author : {{instance.user}}</p>
    <h1>{{ title }} <small>{{ instance.timestamp}}</small></h1>
   
    {{instance.title}}{% if instance.draft %}<span style="color: red;"> DRAFT</span>{%endif%}<br/>
           
    {%if instance.markdown %}
    <div class=' post-detail-item'>{{instance.get_markdown|linebreaks}}</div>
    {%else%}
    {{instance.content|linebreaks}}
    {%endif%}
    <br>
   {%if request.user == instance.user%} <a href="{{instance.get_absolute_url}}edit/" role="button" class="btn btn-success" type="submit"> Edit Post </a>{%endif%}
<hr>

     
    <div>
      <p class="lead">COMMENTS</p>
      <br>
      {%if request.user.is_authenticated %}
      <form method="POST" action=".">{% csrf_token %}
      {{comment_form|crispy}}
      <button type="submit"  class="btn btn-default">Post Comments</button>
      </form>
      {%else%}
      
      {%endif%}
      {% for com in comment %}
    <blockquote class="blockquote">
        <p class="mb-0">{{com.content}}</p>
        <footer class="blockquote-footer">via {{com.user.username}} | {{com.timestamp|timesince}} ago | {% if com.children.count > 1 %}{{com.children.count}} Replies to this thread| {% else %}{{com.children.count}} Reply{% endif %} | <a href="#" class="comment-reply-btn">Reply</a> | <a href="{{com.get_absolute_url}}" class="" data-toggle="tooltip" title="see all Comments">thread</a>
          </footer>
      <div class="comment-reply" style="display: block;">
        {% for child in com.children %}

        
          <blockquote class="blockquote"> 
           <p class="mb-0">{{child.content}}</p>
           <footer class="blockquote-footer">via {{child.user.username}} | {{child.timestamp|timesince}} ago
           </footer>
           
          </blockquote>
        {%endfor%}
        {%if request.user.is_authenticated %}
          <form method="POST" action=".">{%csrf_token%}
            {{comment_form|crispy}}
            <input type="hidden" name="parent_id" value='{{com.id}}'>
          <input type="submit" value="Reply" class="btn btn-default">
         </form>
         {%else%}
         
         {%endif%}
      </div>
    </blockquote>
      <hr>

      {% endfor %}
     
{% endblock %}

 
   

posts/templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block head_extra %}{{form.media}}{% endblock head_extra %}
{% block content%}

	<title>Form</title>
	
		<div class="row">
		
		<div class="col-sm-6">
			<h1>CREATE YOUR BLOGS HERE</h1>
			<hr>
			<form method='POST' action="" enctype="multipart/form-data">{% csrf_token %}
				<div class="form-group">
					
          {{form|crispy}}

            </div>
             {% if instance.get_absolute_url%}<input type='submit' class="btn btn-success" value="Edit Post"/>{%else%}<input type='submit' class="btn btn-success" value="Create"/>{%endif%}
             		
          </form>


        </div>
        <div class="col-sm-6">
			<h1>Preview</h1>
		<hr>
			<div class="content-preview">
				<h3 id="Preview-title" class="break-text"></h3>
				<p id="Preview-content" class="break-text"></p>
			</div>
			
		</div>
		
        </div>
       
       
         <br>
	{% endblock %}

    
    

posts/templates/index.html
{% extends "base.html" %}


{% block content %}
		
		<div class='container col-sm-6'>
		
		<h1>{{title}}</h1>

    {%if request.user.is_authenticated %}
    <span>Hello, {{request.user.username}}</span>
    <a href="/logout"> Logout</a>
    {% endif %}
<hr/>
<form class="GET" action="">
  <div class="input-group">
  <input  class='form-control' type="text" name="q" placeholder="Search Blog" value="{{request.GET.q}}">
  <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
  </div>
</form>
<br>
		{% for i in obj %}
		<div class=" row">
			<div class=" col-sm-12">
		<div class="card img-fluid" >
      {%if i.image %}
      <img class="card-img-top" src={{i.image.url}} >
      {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{i.title}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{i.title}} <small>{{i.timestamp|timesince}} ago</small> </h6>
   {%if i.markdown%}
    <div class=" post-detail-item"><p>{{i.get_markdown|truncatechars_html:9}}</p></div>
   {%else%}
   <p class="card-text">{{i.content|linebreaks|truncatechars:120}}</p>
   {%endif%}

   <p><a href="{{i.get_absolute_url}}" class="btn btn-primary" role="button" >VIEW</a> </p>
    <!--<a href="#" class="card-link">Another link</a>-->
  </div>
   </div>
   </div>

</div>
<hr/>
	    {% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if obj.has_previous %}
            <a href="?page={{ obj.previous_page_number }}{% if request.GET.q%}&q={{request.GET.q}}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ obj.number }} of {{ obj.paginator.num_pages }}.
        </span>

        {% if obj.has_next %}
            <a href="?page={{ obj.next_page_number }}{% if request.GET.q%}&q={{request.GET.q}}{% endif %}">next</a>
        {% endif %}
    </span>
  </div>
</div>








</div>
	
{% endblock %}

<div class="card">
  <div class="card-body">
    This is some text within a card body.
  </div>
</div>

<!--<div class=" row"><div class="col-sm-8 col-sm-offset-2">
		<div class="col-sm-12">
			<div class="thumbnail">
				<div class="caption">

		
		<h3><a href="{{i.get_absolute_url}}">{{i.title}}</a> <small>{{i.timestamp|timesince}}</small></h3>
		<p>{{i.content|linebreaks|truncatechars:120}}</p>
		<p><a href="{{i.get_absolute_url}}" class="btn btn-primary" role="button" >VIEW</a> </p>
	   </div>
	 </div>
   </div>
   
   </div>-->
   <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{{i.image.url}}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

posts/templates/login_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content%}

	<title>{{title}}</title>
	
		
		
		<div class="container col-sm-6 " style="">
			<h1>{{title}}</h1>
			<hr>
			<form method='POST' action="" enctype="multipart/form-data">{% csrf_token %}
				<div class="form-group">
					
   {{form|crispy}}
     
  
    
            </div>
            <div class="container col-sm-3">{% if not title == 'Register'%}<input type='submit' class="btn btn-success" value="Login"/>{%else%}<input type='submit' class="btn btn-success" value="Register"/>{%endif%}</div>		
          </form>
          {% if not title == 'Register'%}<a href="{%url 'register' %}">Not Yet registerd? click here</a>{%endif%}
          <a href="{% url 'posts:list' %} " class="float-right">view as guest</a>
        </div>
    
       
       
         
	{% endblock %}

    
    
{%for field in form%}
 <input type="{% if field.label == 'Password' %}password{% else %}input{% endif %}" placeholder="{{ field.label }}" name="{{ field.name }}" class="form-control" />
     {% endfor %}

posts/templates/thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head%}{{ instance.title }} | {{ block.super }} {% endblock %}
{%block post_detail_link%}
<li class="breadcrumb-item"><a href="{{pre.get_absolute_url}}">{{pre.title|truncatechars:10}}</a></li>
{%endblock%}
{% block content %}
{{object}}

<div class="container col-sm-6 break-text">
   
    <blockquote class="blockquote">
        <p class="mb-0">{{com.content}}</p>
        <footer class="blockquote-footer">via {{com.user.username}} | {{com.timestamp|timesince}} ago | {% if com.children.count > 1 %}{{com.children.count}} Replies to this thread| {% else %}{{com.children.count}} Reply{% endif %} |{% if request.user == com.user%} <a href="{{com.get_delete_url}}" class="btn btn-warning" role="button">Delete the whole thread</a>{% endif %}
          
            <a href="{{pre.get_absolute_url}}">Back</a>
          
          
          </footer>
     
        {% for child in com.children %}

        
          <blockquote class="blockquote"> 
           <p class="mb-0">{{child.content}}</p>
           <footer class="blockquote-footer">via {{child.user.username}} | {{child.timestamp|timesince}} ago | {% if request.user == child.user%}Delet <a href="{{child.get_delete_url}}" class="reply-delete"></a>{% endif %}
           </footer>
           
          </blockquote>
        {%endfor%}
        <br>
        {%if request.user.is_authenticated %}
        <form method="POST" action=".">{%csrf_token%}
            {{form|crispy}}
            <input type="hidden" name="parent_id" value='{{com.id}}'>
          <input type="submit" value="Reply" class="btn btn-default">
         </form>
      {%else%}
      <hr>
      <div class="d-flex p-2" style="display: flex;">You must login to comment!</div>
      {%endif%}
    </blockquote>
</div>
{% endblock %}
 {% url 'thrdel' id=com.id %}
 
    